services:
  nextjs:
    build: .
    command: npm run start
    labels:
      - dev.orbstack.domains=nextjs.arcjet-examples.orb.local
    env_file:
      - .env.local
    ports:
      - 3000
    volumes:
      - .:/app
      - nextjs_node_modules:/app/node_modules
    healthcheck:
      test: ["CMD", "node", "-e", "const http = require('http'); const options = { host: 'localhost', port: 3000, path: '/', timeout: 2000 }; const req = http.request(options, (res) => { process.exit(res.statusCode >= 200 && res.statusCode < 400 ? 0 : 1); }); req.on('error', () => { process.exit(1); }); req.end();"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

volumes:
  nextjs_node_modules:
